### ISSUE TITLE
Cannot verify the XML signed with xmldsig

### ISSUE THREAD

**Issue by ccompass** [benoist/xmldsig#38]
When I try to validate the XML, I got this error

```ruby
Xmldsig::SchemaError: 1:0: ERROR: Element '{http://www.w3.org/2001/10/xml-exc-c14n#}InclusiveNamespaces': No matching global element declaration available, but demanded by the strict wildcard.
	from (irb):882:in `validate_schema'
	from (irb):818:in `valid?'
	from /Users/ben/.rvm/gems/ruby-2.3.1/gems/xmldsig-0.6.3/lib/xmldsig/signed_document.rb:16:in `block in validate'
	from /Users/ben/.rvm/gems/ruby-2.3.1/gems/xmldsig-0.6.3/lib/xmldsig/signed_document.rb:16:in `each'
	from /Users/ben/.rvm/gems/ruby-2.3.1/gems/xmldsig-0.6.3/lib/xmldsig/signed_document.rb:16:in `all?'
	from /Users/ben/.rvm/gems/ruby-2.3.1/gems/xmldsig-0.6.3/lib/xmldsig/signed_document.rb:16:in `validate'
```
Credentials below are all for testing environments.

Here are steps to reproduce:

We first generate a working request payload using SOAPUI. We then removed the digest value and signature value to have the library fill them back in. The digest values are matching. However signature value does not match. And verification does not seem to work either.

```ruby
soap_xml=<<-XML
<soapenv:Envelope xmlns:com="http://common.ws.mcrewards.mastercard.com/" xmlns:diag="http://diagnostic.ws.mcrewards.mastercard.com/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header><wsse:Security soapenv:mustUnderstand="1" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:BinarySecurityToken EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3" wsu:Id="X509-D71773F33CE2CC0B2314968639634068">MIIEFzCCAv+gAwIBAgIQURGfOnFVUl+ai/zvpWDGMDANBgkqhkiG9w0BAQsFADCBhTELMAkGA1UEBhMCQkUxHDAaBgNVBAoTE01hc3RlQ2FyZCBXb3JsZHdpZGUxJDAiBgNVBAsTG0dsb2JhbCBJbmZvcm1hdGlvbiBTZWN1cml0eTEyMDAGA1UEAxMpTWFzdGVyQ2FyZCBQUkQgTWVzc2FnZXMgU2lnbmluZyBTdWIgQ0EgRzIwHhcNMTcwNTA1MjAwOTE3WhcNMjEwNTA0MjAwNjI2WjCBpjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAklMMRAwDgYDVQQHEwdDaGljYWdvMSowKAYDVQQKEyFNYXN0ZXJDYXJkIFdvcmxkd2lkZSAtIFNpZ25pbmcgU1cxDjAMBgNVBAsTBUNIUyAwMRgwFgYDVQQDEw9tdGYuQ0hTLkdyb3Vwb24xIjAgBgkqhkiG9w0BCQEWE2pzaGFycGVAZ3JvdXBvbi5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDoNF/lscz4o8mIkHNW7LzVp26j76fKtJKwXb2veskorB3tx0TowNUoXKQegTqxj/1gYpBYvgj7b8gSTDIklNAomfnpYsfn4EQo2xiQCukAusxoskBpbkYm+9F1Cn4uV5cSE6VBSBVUAJ2DTz/EUNtbV4TJXrRVcp12i7EtnhgwETH1QKlUa6UsYUEysgQfi/e8cDI5M0l44rRlG59Ek20xGG/AXdBXryB9612ICGPT9mLsdl1z36WSlSO+KBV/KrdTjVYTFVVh6Fvc1/jAl7q7qiPGHQMF/+/+U6GT8VMi+0Vupf2iEB9xHOP/CpVRzooJGHLnoKc9OQPbbU9n2NTdAgMBAAGjYDBeMB8GA1UdIwQYMBaAFOugEneCU/RYWK8B6eH/ZAU+R9mqMAwGA1UdEwQFMAMCAQAwDgYDVR0PAQH/BAQDAgeAMB0GA1UdDgQWBBRHloHRYdR6KzQkqP6/M0fKNEA4+jANBgkqhkiG9w0BAQsFAAOCAQEAtqDvao5D1jqXqP+F7s2CcvB983OJ3IGBYm3EDZe0GjKOTl+m2i6weywQR9SoXxijdPRS1xrLS2V5kxjGe9Izz73At5G0K+7KLKbXK8a2doih+Qp+6eZsgX3giN14mjuaz1wyHl/qMaKSf8EaCKZEojJo29INoQm8DzgINnagFhXLMVwHLwSC4Jb8/ely7MJMZQZCQW/iiS7mPIQOpf21xBflNTsYSne9Cg8jobm6C70gsIWXOLAQ6pWwPY5b6JP+358WfdqsB6cQt38ZMSu1x8NFCy9JlKRSaWdtD9FiKOuyFUTCnaIREPEUs+OKKbiJV2BwifND4Rq1D+1bihhFMA==</wsse:BinarySecurityToken><ds:Signature Id="SIG-D71773F33CE2CC0B23149686396340912" xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces PrefixList="com diag soapenv" xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:CanonicalizationMethod><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><ds:Reference URI="#id-E2649BBBB36523B91E1496765834735137"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces PrefixList="diag soapenv" xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>qj1ZEhGDmqKMMTywUX/pZj7R9CheNkxBmh6oOUTAf6w=</ds:DigestValue></ds:Reference><ds:Reference URI="#id-D71773F33CE2CC0B23149686396340711"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces PrefixList="com diag" xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>n9WV45tts/yfn3+gkJ4CbGq3kCdBwFvPI2AaBbwvTGE=</ds:DigestValue></ds:Reference><ds:Reference URI="#TS-D71773F33CE2CC0B2314968639634057"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces PrefixList="wsse com diag soapenv" xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>pPU4kqf+uDfhiC1PV4htHcfp3JR+Ib6azGige+0rTz4=</ds:DigestValue></ds:Reference><ds:Reference URI="#X509-D71773F33CE2CC0B2314968639634068"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces PrefixList="" xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>vdw/kh2A//41tj/yrmSJA4GQ76XqUrabHiyFh6Fqx00=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>VK6EYm0vf8cEBW/CDbHyDXexRw/+27JeG59iZ5c2XGnLy5LB7CvwAX0hCmfPpV0QJd90+yfH6o3A
J5/kGdAZcxQUACMnp/YwksRsYcIS8VY43MdC7xpeaatM+2aWCCZRXkCYlXLyI6cmqBwTqWzZktar
A5ilaZlTQ9ibTe5K9IYUjm03g/NSVEsxqoU5vP55JeL/e+M0/+8arGn67p83Vdjv4RJ/sWnjY4Fn
yU5bsvXBHsVERFeaK+9DklQ09JWw32diipGGpaVIS0uHFNakzTLUPsrNDLQ4oIa1sgs/NUV+y+O6
xZ97YKgdttxN0RF0CtO4+8kDuVzkWt+abWYpNQ==</ds:SignatureValue><ds:KeyInfo Id="KI-D71773F33CE2CC0B2314968639634069"><wsse:SecurityTokenReference wsu:Id="STR-D71773F33CE2CC0B23149686396340610"><wsse:Reference URI="#X509-D71773F33CE2CC0B2314968639634068" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/></wsse:SecurityTokenReference></ds:KeyInfo></ds:Signature><wsu:Timestamp wsu:Id="TS-D71773F33CE2CC0B2314968639634057"><wsu:Created>2017-06-07T19:32:43Z</wsu:Created><wsu:Expires>2017-06-07T19:37:43Z</wsu:Expires></wsu:Timestamp></wsse:Security>
      <com:identity wsu:Id="id-E2649BBBB36523B91E1496765834735137" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
         <com:appID>00000000000000000000</com:appID>
         <com:institutionName>groupon</com:institutionName>
      </com:identity>
   </soapenv:Header>
   <soapenv:Body wsu:Id="id-D71773F33CE2CC0B23149686396340711" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
      <diag:doEcho>Ben</diag:doEcho>
   </soapenv:Body>
</soapenv:Envelope>
XML

stripped_xml = soap_xml.
  gsub(/\<ds:DigestValue\>.*?\<\/ds:DigestValue\>/m,"<ds:DigestValue></ds:DigestValue>").
  gsub(/\<ds:SignatureValue\>.*?\<\/ds:SignatureValue\>/m,"<ds:SignatureValue></ds:SignatureValue>").strip

private_key = OpenSSL::PKey::RSA.new(File.read("test.key"))

unsigned_document = Xmldsig::SignedDocument.new(stripped_xml)
signed_xml = unsigned_document.sign(private_key)

signed_document = Xmldsig::SignedDocument.new(signed_xml)
Xmldsig::SignedDocument.new(signed_document.sign(private_key)).
  validate(OpenSSL::X509::Certificate.new(File.read("test.crt")))

```

[test_credentials.zip](https://github.com/benoist/xmldsig/files/1059403/test_credentials.zip)

**Comment by ccompass** [comment]
Hey I think I found out the problem. There is some brokenness when it is handling c14n algo( http://www.w3.org/TR/2001/REC-xml-c14n-20010315) vs (http://www.w3.org/2001/10/xml-exc-c14n#). Do we have test for both? This may not be a problem with this library. For now, we can close this issue. thanks a lot!!!
